<?php

namespace Database\Seeders;

use App\Models\Theme;
use Illuminate\Database\Seeder;

class ThemeSeeder extends Seeder
{
    public function run(): void
    {
        $themes = [
            [
                'name' => 'Ocean Blue',
                'slug' => 'ocean-blue',
                'preview' => 'images/site-templates/ocean-blue.png',
                'variables' => [
                    'primary' => '#2563eb',
                    'secondary' => '#0f172a',
                    'accent' => '#38bdf8',
                    'background' => '#ffffff',
                    'surface' => '#f8fafc',
                    'text' => '#0f172a',
                    'muted' => '#64748b',
                    'border' => '#e2e8f0',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'radius' => '14px',
                    'shadow' => 'soft',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Sunset Luxe',
                'slug' => 'sunset-luxe',
                'preview' => 'images/site-templates/sunset-luxe.png',
                'variables' => [
                    'primary' => '#f97316',
                    'secondary' => '#111827',
                    'accent' => '#facc15',
                    'background' => '#fff7ed',
                    'surface' => '#ffffff',
                    'text' => '#1f2937',
                    'muted' => '#78716c',
                    'border' => '#fed7aa',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'Georgia, "Times New Roman", serif',
                    'radius' => '18px',
                    'shadow' => 'medium',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Wild Nature',
                'slug' => 'wild-nature',
                'preview' => 'images/site-templates/mountain-adventure.png',
                'variables' => [
                    'primary' => '#2f7d55',
                    'secondary' => '#102a2f',
                    'accent' => '#86efac',
                    'background' => '#ffffff',
                    'surface' => '#f0fdf4',
                    'text' => '#0f172a',
                    'muted' => '#64748b',
                    'border' => '#bbf7d0',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'radius' => '14px',
                    'shadow' => 'soft',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Urban Blue',
                'slug' => 'urban-blue',
                'preview' => 'images/site-templates/city-escape.png',
                'variables' => [
                    'primary' => '#0ea5e9',
                    'secondary' => '#172554',
                    'accent' => '#f97316',
                    'background' => '#ffffff',
                    'surface' => '#f8fafc',
                    'text' => '#0f172a',
                    'muted' => '#64748b',
                    'border' => '#dbeafe',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'radius' => '12px',
                    'shadow' => 'soft',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Coastal Glow',
                'slug' => 'coastal-glow',
                'preview' => 'images/site-templates/beach-paradise.png',
                'variables' => [
                    'primary' => '#0891b2',
                    'secondary' => '#164e63',
                    'accent' => '#fbbf24',
                    'background' => '#ffffff',
                    'surface' => '#ecfeff',
                    'text' => '#0f172a',
                    'muted' => '#64748b',
                    'border' => '#a5f3fc',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'radius' => '16px',
                    'shadow' => 'soft',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Heritage Rose',
                'slug' => 'heritage-rose',
                'preview' => 'images/site-templates/culture-journey.png',
                'variables' => [
                    'primary' => '#be456b',
                    'secondary' => '#431a2a',
                    'accent' => '#f59e0b',
                    'background' => '#ffffff',
                    'surface' => '#fff1f2',
                    'text' => '#0f172a',
                    'muted' => '#64748b',
                    'border' => '#fecdd3',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'Georgia, "Times New Roman", serif',
                    'radius' => '14px',
                    'shadow' => 'medium',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Mountain Escape',
                'slug' => 'mountain-escape',
                'preview' => 'images/site-templates/mountain-adventure.png',
                'variables' => [
                    'primary' => '#2fb678',
                    'secondary' => '#12352d',
                    'accent' => '#9ae6b4',
                    'background' => '#ffffff',
                    'surface' => '#edfdf5',
                    'text' => '#0f172a',
                    'muted' => '#64748b',
                    'border' => '#c9f5dc',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'radius' => '14px',
                    'shadow' => 'soft',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'City Journey',
                'slug' => 'city-journey',
                'preview' => 'images/site-templates/city-escape.png',
                'variables' => [
                    'primary' => '#6d5dfc',
                    'secondary' => '#31154f',
                    'accent' => '#ff7ab6',
                    'background' => '#ffffff',
                    'surface' => '#f6f3ff',
                    'text' => '#111827',
                    'muted' => '#667085',
                    'border' => '#ddd6fe',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'radius' => '16px',
                    'shadow' => 'medium',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Desert Roads',
                'slug' => 'desert-roads',
                'preview' => 'images/site-templates/sunset-luxe.png',
                'variables' => [
                    'primary' => '#d97706',
                    'secondary' => '#4a2f13',
                    'accent' => '#fbbf24',
                    'background' => '#fffaf0',
                    'surface' => '#fff7ed',
                    'text' => '#231a12',
                    'muted' => '#7c6a55',
                    'border' => '#fed7aa',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'Georgia, "Times New Roman", serif',
                    'radius' => '18px',
                    'shadow' => 'soft',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Urban Life',
                'slug' => 'urban-life',
                'preview' => 'images/site-templates/city-escape.png',
                'variables' => [
                    'primary' => '#111827',
                    'secondary' => '#020617',
                    'accent' => '#60a5fa',
                    'background' => '#ffffff',
                    'surface' => '#f8fafc',
                    'text' => '#0f172a',
                    'muted' => '#64748b',
                    'border' => '#cbd5e1',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'radius' => '10px',
                    'shadow' => 'strong',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Beach Paradise',
                'slug' => 'beach-paradise',
                'preview' => 'images/site-templates/beach-paradise.png',
                'variables' => [
                    'primary' => '#06b6d4',
                    'secondary' => '#075985',
                    'accent' => '#facc15',
                    'background' => '#ffffff',
                    'surface' => '#ecfeff',
                    'text' => '#0f172a',
                    'muted' => '#64748b',
                    'border' => '#a5f3fc',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'radius' => '16px',
                    'shadow' => 'soft',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Culture Journey',
                'slug' => 'culture-journey',
                'preview' => 'images/site-templates/culture-journey.png',
                'variables' => [
                    'primary' => '#9f456f',
                    'secondary' => '#3d1631',
                    'accent' => '#f59e0b',
                    'background' => '#ffffff',
                    'surface' => '#fff1f2',
                    'text' => '#111827',
                    'muted' => '#64748b',
                    'border' => '#fecdd3',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'Georgia, "Times New Roman", serif',
                    'radius' => '14px',
                    'shadow' => 'medium',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
            [
                'name' => 'Wellness Retreat',
                'slug' => 'wellness-retreat',
                'preview' => 'images/site-templates/mountain-adventure.png',
                'variables' => [
                    'primary' => '#14b8a6',
                    'secondary' => '#134e4a',
                    'accent' => '#ccfbf1',
                    'background' => '#ffffff',
                    'surface' => '#f0fdfa',
                    'text' => '#0f172a',
                    'muted' => '#64748b',
                    'border' => '#99f6e4',
                    'bodyFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'headingFont' => 'ui-sans-serif, system-ui, sans-serif',
                    'radius' => '24px',
                    'shadow' => 'soft',
                ],
                'status' => Theme::STATUS_ACTIVE,
            ],
        ];

        foreach ($themes as $theme) {
            Theme::updateOrCreate(
                ['slug' => $theme['slug']],
                $theme
            );
        }
    }
}
