<?php

return [
    'minimums' => [
        'published_destinations' => 3,
        'featured_destinations' => 3,
        'published_offers' => 3,
        'special_offers' => 3,
    ],

    'media' => [
        'marrakech-medina' => [
            'title' => 'Marrakech Medina',
            'alt_text' => 'Warm sunset over Marrakech travel illustration',
            'colors' => ['#f97316', '#ef4444', '#111827'],
        ],
        'santorini-coast' => [
            'title' => 'Santorini Coast',
            'alt_text' => 'Blue coast travel illustration',
            'colors' => ['#0ea5e9', '#2563eb', '#f8fafc'],
        ],
        'bali-retreat' => [
            'title' => 'Bali Retreat',
            'alt_text' => 'Tropical retreat travel illustration',
            'colors' => ['#10b981', '#14b8a6', '#ecfeff'],
        ],
        'paris-city-lights' => [
            'title' => 'Paris City Lights',
            'alt_text' => 'Paris city lights travel illustration',
            'colors' => ['#6366f1', '#a855f7', '#111827'],
        ],
        'dubai-luxury-escape' => [
            'title' => 'Dubai Luxury Escape',
            'alt_text' => 'Luxury city escape travel illustration',
            'colors' => ['#f59e0b', '#0f172a', '#fef3c7'],
        ],
        'istanbul-heritage-tour' => [
            'title' => 'Istanbul Heritage Tour',
            'alt_text' => 'Historic city travel illustration',
            'colors' => ['#dc2626', '#1d4ed8', '#f8fafc'],
        ],
    ],

    'destinations' => [
        [
            'name' => 'Marrakech Medina',
            'slug' => 'marrakech-medina',
            'country' => 'Morocco',
            'continent' => 'africa',
            'region' => 'Marrakech-Safi',
            'description' => 'A warm city escape with riads, souks, gardens, and guided cultural walks.',
            'travel_types' => ['cultural', 'city', 'desert'],
            'ideal_months' => [3, 4, 5, 9, 10, 11],
            'practical_information' => 'Light clothing is suitable during the day, with an extra layer for cool evenings. The medina is best explored on foot with comfortable shoes.',
            'latitude' => 31.6294723,
            'longitude' => -7.9810845,
            'is_featured' => true,
            'media' => 'marrakech-medina',
        ],
        [
            'name' => 'Santorini Coast',
            'slug' => 'santorini-coast',
            'country' => 'Greece',
            'continent' => 'europe',
            'region' => 'Cyclades',
            'description' => 'Whitewashed villages, volcanic beaches, sunset cruises, and relaxed island stays.',
            'travel_types' => ['beach', 'cultural', 'wellness'],
            'ideal_months' => [5, 6, 7, 8, 9],
            'practical_information' => 'Reserve ferry connections early in summer and bring sun protection. Village lanes include many stairs and uneven surfaces.',
            'latitude' => 36.3931562,
            'longitude' => 25.4615092,
            'is_featured' => true,
            'media' => 'santorini-coast',
        ],
        [
            'name' => 'Bali Retreat',
            'slug' => 'bali-retreat',
            'country' => 'Indonesia',
            'continent' => 'asia',
            'region' => 'Bali',
            'description' => 'Rice terraces, wellness resorts, temples, and private tropical experiences.',
            'travel_types' => ['wellness', 'nature', 'cultural'],
            'ideal_months' => [4, 5, 6, 7, 8, 9, 10],
            'practical_information' => 'Temple visits require respectful clothing. Allow extra road time between regions and keep rain protection during the shoulder season.',
            'latitude' => -8.4095178,
            'longitude' => 115.188916,
            'is_featured' => true,
            'media' => 'bali-retreat',
        ],
        [
            'name' => 'Paris City Lights',
            'slug' => 'paris-city-lights',
            'country' => 'France',
            'continent' => 'europe',
            'region' => 'Ile-de-France',
            'description' => 'Boutique hotels, museum passes, river walks, and elegant city breaks.',
            'travel_types' => ['city', 'cultural'],
            'ideal_months' => [4, 5, 6, 7, 8, 9, 10],
            'practical_information' => 'Book major museums in advance and use public transport for the easiest connections between neighbourhoods.',
            'latitude' => 48.856614,
            'longitude' => 2.3522219,
            'is_featured' => false,
            'media' => 'paris-city-lights',
        ],
        [
            'name' => 'Dubai Luxury Escape',
            'slug' => 'dubai-luxury-escape',
            'country' => 'United Arab Emirates',
            'continent' => 'asia',
            'region' => 'Dubai',
            'description' => 'Premium hotels, desert dinners, skyline views, and private transfers.',
            'travel_types' => ['city', 'desert', 'family'],
            'ideal_months' => [1, 2, 3, 11, 12],
            'practical_information' => 'Winter offers the most comfortable outdoor temperatures. Respect local dress guidance in cultural and religious sites.',
            'latitude' => 25.2048493,
            'longitude' => 55.2707828,
            'is_featured' => false,
            'media' => 'dubai-luxury-escape',
        ],
        [
            'name' => 'Istanbul Heritage Tour',
            'slug' => 'istanbul-heritage-tour',
            'country' => 'Turkey',
            'continent' => 'asia',
            'region' => 'Istanbul',
            'description' => 'Historic quarters, Bosphorus views, food tours, and curated culture days.',
            'travel_types' => ['cultural', 'city'],
            'ideal_months' => [4, 5, 6, 9, 10],
            'practical_information' => 'Carry a scarf for mosque visits and plan extra time around peak-hour traffic. A transit card is useful for ferries and trams.',
            'latitude' => 41.0082376,
            'longitude' => 28.9783589,
            'is_featured' => false,
            'media' => 'istanbul-heritage-tour',
        ],
    ],

    'offers' => [
        [
            'title' => 'Marrakech Weekend Escape',
            'slug' => 'marrakech-weekend-escape',
            'destination' => 'marrakech-medina',
            'description' => 'Three days with a riad stay, airport transfers, medina guide, and dinner experience.',
            'summary' => 'A compact cultural escape through the medina, gardens and flavours of Marrakech.',
            'price' => 390,
            'duration_days' => 3,
            'itinerary' => [
                ['day' => 1, 'title' => 'Arrival and riad welcome', 'description' => 'Private airport transfer, check-in and a relaxed first evening.'],
                ['day' => 2, 'title' => 'Medina with a local guide', 'description' => 'Explore historic quarters, artisan souks and a traditional dinner.'],
                ['day' => 3, 'title' => 'Gardens and departure', 'description' => 'Morning garden visit followed by your private transfer.'],
            ],
            'inclusions' => ['Two nights in a riad', 'Private airport transfers', 'Guided medina visit', 'One dinner experience'],
            'exclusions' => ['Flights', 'Personal expenses', 'Travel insurance'],
            'practical_information' => 'The programme involves walking on uneven lanes. Comfortable footwear is recommended.',
            'is_special' => true,
            'media' => 'marrakech-medina',
        ],
        [
            'title' => 'Santorini Summer Deal',
            'slug' => 'santorini-summer-deal',
            'destination' => 'santorini-coast',
            'description' => 'Island stay with breakfast, sunset cruise, and flexible travel dates.',
            'summary' => 'Five sunlit days combining caldera views, island villages and a sunset cruise.',
            'price' => 780,
            'duration_days' => 5,
            'itinerary' => [
                ['day' => 1, 'title' => 'Island arrival', 'description' => 'Transfer to your hotel and time to settle beside the caldera.'],
                ['day' => 2, 'title' => 'Villages and viewpoints', 'description' => 'Discover traditional villages with time for independent exploration.'],
                ['day' => 4, 'title' => 'Sunset cruise', 'description' => 'Sail along the volcanic coast with dinner on board.'],
            ],
            'inclusions' => ['Four nights with breakfast', 'Arrival transfer', 'Village tour', 'Sunset cruise'],
            'exclusions' => ['Flights or ferry tickets', 'Optional activities', 'Travel insurance'],
            'practical_information' => 'Ferry and flight schedules are confirmed separately according to your chosen dates.',
            'is_special' => true,
            'media' => 'santorini-coast',
        ],
        [
            'title' => 'Bali Wellness Week',
            'slug' => 'bali-wellness-week',
            'destination' => 'bali-retreat',
            'description' => 'Wellness resort package with yoga sessions, temple tour, and private driver.',
            'summary' => 'A restorative week of yoga, temples, rice terraces and private island travel.',
            'price' => 950,
            'duration_days' => 7,
            'itinerary' => [
                ['day' => 1, 'title' => 'Private arrival', 'description' => 'Meet your driver and settle into the wellness resort.'],
                ['day' => 3, 'title' => 'Temples and terraces', 'description' => 'A guided cultural day through central Bali.'],
                ['day' => 6, 'title' => 'Wellness at your pace', 'description' => 'Yoga, spa time and a final private dinner.'],
            ],
            'inclusions' => ['Six nights at a wellness resort', 'Daily breakfast', 'Private driver on programme days', 'Yoga sessions'],
            'exclusions' => ['International flights', 'Visa fees if applicable', 'Optional spa treatments'],
            'practical_information' => 'Activities can be adjusted to your preferred wellness level before confirmation.',
            'is_special' => true,
            'media' => 'bali-retreat',
        ],
        [
            'title' => 'Paris Romantic Getaway',
            'slug' => 'paris-romantic-getaway',
            'destination' => 'paris-city-lights',
            'description' => 'Four-night city break with boutique hotel, museum pass, and dinner reservation support.',
            'summary' => 'An elegant Paris city break with culture, neighbourhood walks and a boutique stay.',
            'price' => 620,
            'duration_days' => 4,
            'itinerary' => [
                ['day' => 1, 'title' => 'Paris arrival', 'description' => 'Hotel check-in and a self-guided neighbourhood walk.'],
                ['day' => 2, 'title' => 'Art and river views', 'description' => 'Use your museum pass and enjoy an evening by the Seine.'],
                ['day' => 4, 'title' => 'Final morning', 'description' => 'Breakfast and free time before departure.'],
            ],
            'inclusions' => ['Three hotel nights', 'Breakfast', 'Museum pass', 'Restaurant reservation support'],
            'exclusions' => ['Transport to Paris', 'Local transport', 'Meals not listed'],
            'practical_information' => 'Museum entrance times are subject to availability and confirmed with the final itinerary.',
            'is_special' => false,
            'media' => 'paris-city-lights',
        ],
        [
            'title' => 'Dubai Premium Package',
            'slug' => 'dubai-premium-package',
            'destination' => 'dubai-luxury-escape',
            'description' => 'Luxury stay with private transfers, desert dinner, marina cruise, and concierge support.',
            'summary' => 'Premium Dubai hospitality with private transfers, desert dining and skyline experiences.',
            'price' => 1250,
            'duration_days' => 6,
            'itinerary' => [
                ['day' => 1, 'title' => 'VIP arrival', 'description' => 'Private transfer and premium hotel check-in.'],
                ['day' => 3, 'title' => 'Desert evening', 'description' => 'Private desert experience followed by dinner.'],
                ['day' => 5, 'title' => 'Marina cruise', 'description' => 'Relax on a curated evening cruise with skyline views.'],
            ],
            'inclusions' => ['Five premium hotel nights', 'Private airport transfers', 'Desert dinner', 'Marina cruise'],
            'exclusions' => ['Flights', 'Tourism taxes paid locally', 'Optional experiences'],
            'practical_information' => 'Hotel and experience availability must be reconfirmed for the selected travel dates.',
            'is_special' => false,
            'media' => 'dubai-luxury-escape',
        ],
        [
            'title' => 'Istanbul Culture Break',
            'slug' => 'istanbul-culture-break',
            'destination' => 'istanbul-heritage-tour',
            'description' => 'Guided heritage days, Bosphorus dinner cruise, and centrally located hotel.',
            'summary' => 'Four days of heritage, flavours and Bosphorus views from a central Istanbul base.',
            'price' => 540,
            'duration_days' => 4,
            'itinerary' => [
                ['day' => 1, 'title' => 'Old city arrival', 'description' => 'Transfer and time to explore around your central hotel.'],
                ['day' => 2, 'title' => 'Heritage highlights', 'description' => 'Guided visits through the historic peninsula.'],
                ['day' => 3, 'title' => 'Bosphorus evening', 'description' => 'Local food discoveries followed by a dinner cruise.'],
            ],
            'inclusions' => ['Three hotel nights', 'Breakfast', 'Guided heritage day', 'Bosphorus dinner cruise'],
            'exclusions' => ['Flights', 'Visa if required', 'Personal expenses'],
            'practical_information' => 'Religious sites may adjust visiting hours. The final schedule will reflect local opening times.',
            'is_special' => false,
            'media' => 'istanbul-heritage-tour',
        ],
    ],
];
