<?php

return [
    'minimums' => [
        'published_destinations' => 3,
        'featured_destinations' => 3,
        'published_offers' => 3,
        'special_offers' => 3,
    ],

    'media' => [
        'marrakech-medina' => [
            'title' => 'Marrakech Medina',
            'alt_text' => 'Warm sunset over Marrakech travel illustration',
            'colors' => ['#f97316', '#ef4444', '#111827'],
        ],
        'santorini-coast' => [
            'title' => 'Santorini Coast',
            'alt_text' => 'Blue coast travel illustration',
            'colors' => ['#0ea5e9', '#2563eb', '#f8fafc'],
        ],
        'bali-retreat' => [
            'title' => 'Bali Retreat',
            'alt_text' => 'Tropical retreat travel illustration',
            'colors' => ['#10b981', '#14b8a6', '#ecfeff'],
        ],
        'paris-city-lights' => [
            'title' => 'Paris City Lights',
            'alt_text' => 'Paris city lights travel illustration',
            'colors' => ['#6366f1', '#a855f7', '#111827'],
        ],
        'dubai-luxury-escape' => [
            'title' => 'Dubai Luxury Escape',
            'alt_text' => 'Luxury city escape travel illustration',
            'colors' => ['#f59e0b', '#0f172a', '#fef3c7'],
        ],
        'istanbul-heritage-tour' => [
            'title' => 'Istanbul Heritage Tour',
            'alt_text' => 'Historic city travel illustration',
            'colors' => ['#dc2626', '#1d4ed8', '#f8fafc'],
        ],
    ],

    'destinations' => [
        [
            'name' => 'Marrakech Medina',
            'slug' => 'marrakech-medina',
            'country' => 'Morocco',
            'description' => 'A warm city escape with riads, souks, gardens, and guided cultural walks.',
            'is_featured' => true,
            'media' => 'marrakech-medina',
        ],
        [
            'name' => 'Santorini Coast',
            'slug' => 'santorini-coast',
            'country' => 'Greece',
            'description' => 'Whitewashed villages, volcanic beaches, sunset cruises, and relaxed island stays.',
            'is_featured' => true,
            'media' => 'santorini-coast',
        ],
        [
            'name' => 'Bali Retreat',
            'slug' => 'bali-retreat',
            'country' => 'Indonesia',
            'description' => 'Rice terraces, wellness resorts, temples, and private tropical experiences.',
            'is_featured' => true,
            'media' => 'bali-retreat',
        ],
        [
            'name' => 'Paris City Lights',
            'slug' => 'paris-city-lights',
            'country' => 'France',
            'description' => 'Boutique hotels, museum passes, river walks, and elegant city breaks.',
            'is_featured' => false,
            'media' => 'paris-city-lights',
        ],
        [
            'name' => 'Dubai Luxury Escape',
            'slug' => 'dubai-luxury-escape',
            'country' => 'United Arab Emirates',
            'description' => 'Premium hotels, desert dinners, skyline views, and private transfers.',
            'is_featured' => false,
            'media' => 'dubai-luxury-escape',
        ],
        [
            'name' => 'Istanbul Heritage Tour',
            'slug' => 'istanbul-heritage-tour',
            'country' => 'Turkey',
            'description' => 'Historic quarters, Bosphorus views, food tours, and curated culture days.',
            'is_featured' => false,
            'media' => 'istanbul-heritage-tour',
        ],
    ],

    'offers' => [
        [
            'title' => 'Marrakech Weekend Escape',
            'slug' => 'marrakech-weekend-escape',
            'destination' => 'marrakech-medina',
            'description' => 'Three days with a riad stay, airport transfers, medina guide, and dinner experience.',
            'price' => 390,
            'duration_days' => 3,
            'is_special' => true,
            'media' => 'marrakech-medina',
        ],
        [
            'title' => 'Santorini Summer Deal',
            'slug' => 'santorini-summer-deal',
            'destination' => 'santorini-coast',
            'description' => 'Island stay with breakfast, sunset cruise, and flexible travel dates.',
            'price' => 780,
            'duration_days' => 5,
            'is_special' => true,
            'media' => 'santorini-coast',
        ],
        [
            'title' => 'Bali Wellness Week',
            'slug' => 'bali-wellness-week',
            'destination' => 'bali-retreat',
            'description' => 'Wellness resort package with yoga sessions, temple tour, and private driver.',
            'price' => 950,
            'duration_days' => 7,
            'is_special' => true,
            'media' => 'bali-retreat',
        ],
        [
            'title' => 'Paris Romantic Getaway',
            'slug' => 'paris-romantic-getaway',
            'destination' => 'paris-city-lights',
            'description' => 'Four-night city break with boutique hotel, museum pass, and dinner reservation support.',
            'price' => 620,
            'duration_days' => 4,
            'is_special' => false,
            'media' => 'paris-city-lights',
        ],
        [
            'title' => 'Dubai Premium Package',
            'slug' => 'dubai-premium-package',
            'destination' => 'dubai-luxury-escape',
            'description' => 'Luxury stay with private transfers, desert dinner, marina cruise, and concierge support.',
            'price' => 1250,
            'duration_days' => 6,
            'is_special' => false,
            'media' => 'dubai-luxury-escape',
        ],
        [
            'title' => 'Istanbul Culture Break',
            'slug' => 'istanbul-culture-break',
            'destination' => 'istanbul-heritage-tour',
            'description' => 'Guided heritage days, Bosphorus dinner cruise, and centrally located hotel.',
            'price' => 540,
            'duration_days' => 4,
            'is_special' => false,
            'media' => 'istanbul-heritage-tour',
        ],
    ],
];
